disabled_rules:
- leading_whitespace
- trailing_whitespace
- cyclomatic_complexity
- force_try

excluded:
  - Pods/
  - UniTice/Sources/Models/University
  - UniTice/Utils/SwiftGen
  - UniTice/Sources/AppDelegate.swift

line_length:
  warning: 99
  error: 120
