disabled_rules:
- leading_whitespace
- trailing_whitespace
- cyclomatic_complexity

excluded:
  - Pods/
  - UniTice/Model
  - UniTice/SwiftGens
  - UniTice/Supporting Files/AppDelegate.swift
line_length:
  warning: 99
  error: 120
